version: '3.7'

services:
  mock_server1:  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8080" 
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8001  #порт для первого сервера
      - MOCK_SERVER_NUMBER=1  

  mock_server2:  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8002  #порт для второго сервера
      - MOCK_SERVER_NUMBER=2

volumes:
  config:

networks:
  network:
    driver: bridge
